
services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - ./data/minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - pipeline

  postgres_db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin        # user mặc định
      POSTGRES_PASSWORD: admin123 # mật khẩu
      POSTGRES_DB: etl           # tên database mặc định
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    networks:
      - pipeline
  
  postgres-metabase:
    image: postgres:latest
    container_name: postgres-metabase
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=metabase
    volumes:
      - ./data/postgres_metabase_data:/var/lib/postgresql/data
    networks:
      - pipeline
  metabase:
    image: metabase/metabase
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_HOST=postgres-metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=admin
      - MB_DB_PASS=admin
      - MB_DB_DBNAME=metabase
    depends_on:
      - postgres-metabase
    networks:
      - pipeline